# Generated by Django 5.2.6 on 2025-10-10 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studygroup_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworknote',
            name='text',
        ),
        migrations.AddField(
            model_name='homeworknote',
            name='category',
            field=models.CharField(choices=[('Q', 'Question'), ('T', 'Tip'), ('R', 'Resource')], default='Q', max_length=1),
        ),
        migrations.AddField(
            model_name='homeworknote',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homeworknote',
            name='grade',
            field=models.IntegerField(choices=[(9, '9'), (10, '10'), (11, '11'), (12, '12')], default=9),
        ),
        migrations.AddField(
            model_name='homeworknote',
            name='note_type',
            field=models.CharField(choices=[('HW', 'Homework'), ('EX', 'Exam Prep'), ('GEN', 'General')], default='HW', max_length=3),
        ),
        migrations.AddField(
            model_name='homeworknote',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='HomeworkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_comments', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.homeworknote')),
            ],
        ),
    ]
