# Generated by Django 5.2.7 on 2025-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
